# This is just for documenting
# This will not be redeployed after each merge
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maestro-pvc-dev
  namespace: 24ws-ase-pr-qse-05
spec:
   storageClassName: rook-cephfs
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
