---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-pvc
  labels:
    app: cloudbeaver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
      - name: cloudbeaver
        image: dbeaver/cloudbeaver:latest
        ports:
        - containerPort: 8978
          name: http
          protocol: TCP
        volumeMounts:
        - name: cloudbeaver-storage
          mountPath: /opt/cloudbeaver/workspace
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8978
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8978
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: cloudbeaver-storage
        persistentVolumeClaim:
          claimName: cloudbeaver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  type: NodePort
  ports:
  - port: 8978
    targetPort: 8978
    nodePort: 30978
    protocol: TCP
    name: http
  selector:
    app: cloudbeaver
