---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:latest
        ports:
        - containerPort: 1025
          name: smtp
          protocol: TCP
        - containerPort: 8025
          name: http
          protocol: TCP
        env:
        - name: MP_MAX_MESSAGES
          value: "5000"
        - name: MP_SMTP_AUTH_ACCEPT_ANY
          value: "1"
        - name: MP_SMTP_AUTH_ALLOW_INSECURE
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8025
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8025
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  type: NodePort
  ports:
  - port: 1025
    targetPort: 1025
    protocol: TCP
    name: smtp
  - port: 8025
    targetPort: 8025
    nodePort: 30025
    protocol: TCP
    name: http
  selector:
    app: mailpit
