---
apiVersion: v1
kind: ConfigMap
metadata:
  name: menumaestro-config
  labels:
    app: menumaestro
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dev"
  SPRING_DATASOURCE_USERNAME: "db_user"
  MENUMAESTRO_MAIL_HOST: "mailhog"
  MENUMAESTRO_MAIL_PORT: "1025"
  MENUMAESTRO_MAIL_USERNAME: "noreply@menumaestro.local"
  MENUMAESTRO_MAIL_PASSWORD: ""
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
  SPRING_APPLICATION_URI: "http://localhost:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: menumaestro-secret
  labels:
    app: menumaestro
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "u3iGTeLr"
  MENUMAESTRO_SECURITY_JWT_SECRET_KEY: "replace_in_prod_this_is_only_for_testing_purposes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menumaestro
  labels:
    app: menumaestro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menumaestro
  template:
    metadata:
      labels:
        app: menumaestro
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z postgres 5432; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is up - proceeding"
      containers:
      - name: menumaestro
        image: menumaestro:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: menumaestro-config
        - secretRef:
            name: menumaestro-secret
        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: menumaestro
  labels:
    app: menumaestro
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: menumaestro
