spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    driverClassName: org.postgresql.Driver
    hikari:
      username: db_user
      password: u3iGTeLr
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    enabled: true
  application:
    name: MenuMaestro
    uri: http://localhost:8080
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 587
    username: AKIASOVAYIIFE2J23ZVS
    password: BPUsynVUatUIR65qtxyYERVqCGxPFqEGYoTNQkdnhQ/M
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  servlet:
    multipart:
      max-file-size: 5MB


email:
  from_address: asemailer@erlacher.dev
imageBasePath: "/api/v1/images"

security:
  jwt:
    secret-key: ASDHJAJKSDASJHDUIASHDOPIOUIOASRJAKLSDASKLJCKLACASKL
    account-access-token:
      expiration-time: 8h
      role-claim-name: roles
      audience-claim: "account"
    shopping-list-share-token:
      expiration-time: 24h
      audience-claim: "shopping-list"
  password-reset:
    expiration-time: 15m

logging:
  level:
    root: info
    dev.heinisch.menumaestro.datagen: debug


initial-accounts:
  accounts:
    - username: admin
      password: hallo123
      email: admin@example.com
      first-name: Admin
      last-name: Adminikus
      is-global-admin: true
    - username: user1
      password: hallo123
      email: user1@example.com
      first-name: Max
      last-name: Mustermann
      is-global-admin: false
    - username: user2
      password: hallo123
      email: user2@example.com
      first-name: Maxine
      last-name: Musterfrau
      is-global-admin: false
    - username: user3
      password: hallo123
      email: user3@example.com
      first-name: Just
      last-name: Invited
      is-global-admin: false
    - username: user4
      password: hallo123
      email: user4@example.com
      first-name: InOther
      last-name: Organization
      is-global-admin: false
initial-organizations:
  organizations:
    - name: CoolOrg
      description: The cool organization where almost everyone is.
      members:
        - username: admin
          role: OWNER
        - username: user1
          role: ADMIN
        - username: user2
          role: MEMBER
        - username: user3
          role: INVITED
    - name: LonelyOrg
      description: The organization where the others are.
      members:
        - username: user4
          role: OWNER
        - username: user3
          role: PLANNER

websocket:
  allowed-cross-origin-patterns:
    - "http://localhost:4200"
    - "http://localhost:8080"
    - "moz-extension:*"
  application-prefix: /app
  topics:
    shopping-list-topic-prefix: /shopping-lists
  websocket-path: /ws
