services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=u3iGTeLr
      - POSTGRES_USER=db_user
      - POSTGRES_DB=dev
  app:
    build: ../..
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dev
      - SPRING_DATASOURCE_HIKARI_USERNAME=db_user
      - SPRING_DATASOURCE_HIKARI_PASSWORD=u3iGTeLr
      - SECURITY_JWT_SECRET-KEY=changeinprod
volumes:
  postgres-data:
