openapi: 3.0.0
info:
  title: "Menu Maestro API for Image Upload"
  version: 1.0.0
  description: "A basic file-storage API integrated into Menu Maestro"

servers:
  - url: http://localhost:8080

paths:
  /images:
    post:
      operationId: uploadImage
      tags:
        - images
      summary: "Upload an image"
      description: "Upload an image file, get back an identifier to refer to the record."
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: "Success - Image uploaded successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageUploadResponse"
        401:
          description: "Unauthorized - User needs to be logged in to upload images"
          content:
            application/json:
              schema:
                $ref: 'Common.yaml#/components/schemas/ErrorResponse'
        413:
          description: "Payload too large - Image file is too large"
          content:
            application/json:
              schema:
                $ref: 'Common.yaml#/components/schemas/ErrorResponse'
        415:
          description: "Unsupported Media Type - Image file is not supported"
          content:
            application/json:
              schema:
                $ref: 'Common.yaml#/components/schemas/ErrorResponse'

  /images/{id}:
    get:
      operationId: getImageById
      tags:
        - images
      summary: "Get an image by its identifier"
      description: "Get an image by its identifier. The identifier is returned when the image is uploaded. Response is the image file."
      parameters:
        - $ref: "Common.yaml#/components/parameters/idPathParam"
      responses:
        200:
          description: "Success - Image retrieved successfully"
          content:
            image/*:
              schema:
                type: string
                format: binary
        404:
          description: "Not Found - Image with the specified identifier was not found"
          content:
            application/json:
              schema:
                $ref: 'Common.yaml#/components/schemas/ErrorResponse'
components:
  schemas:
    ImageUploadResponse:
      type: object
      description: "Response object for image upload"
      properties:
        identifier:
          type: string
          description: "Identifier to refer to the uploaded image"
        downloadLink:
          type: string
          description: "Link to download the uploaded image"
      required:
        - identifier
        - downloadLink
