apiVersion: v1
kind: Service
metadata:
  name: menumaestro-environment-service
  namespace: 24ws-ase-pr-qse-05
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: menumaestro-environment
  ports:
    - port: 4200
      name: frontend-environment-port
      protocol: TCP
      targetPort: 4200
    - port: 8080
      name: backend-environment-port
      protocol: TCP
      targetPort: 8080
