openapi: 3.0.0
info:
  title: Menu Maestro API for Image Upload
  version: 1.0.0
  description: A basic file-storage API integrated into Menu Maestro

servers:
  - url: http://localhost:8080/api/v1

paths:
  /images:
    post:
      operationId: "uploadImage"
      tags:
        - Images
      description: "Upload an image file, get back an identifier to refer to the record."
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary

      responses:
        "200":
          description: "Upload successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageUploadResponseDto"
        "403":
          description: "Not logged in"
          content:
            application/json:
              schema:
                $ref: "ErrorResponse.yaml#/components/responses/ErrorResponse"
  /images/{id}:
    get:
      operationId: downloadImage
      tags:
        - Images
      description: "Download an image"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success Response
          content:
            image/*:
              schema:
                type: string
                format: binary
        "404":
          description: Image not found
          content:
            application/json:
              schema:
                $ref: "ErrorResponse.yaml#/components/responses/ErrorResponse"
components:
  schemas:
    ImageUploadResponseDto:
      type: object
      required:
        - identifier
        - downloadLink
      properties:
        identifier:
          type: string
        downloadLink:
          type: string
