openapi: 3.0.0

info:
  title: Menu Maestro cooking appliances API
  version: 1.0.0
  description: The API for the Menu-Maestro cooking appliances

paths: {}

components:
  schemas:
    PaginationResponse:
      description: "base object for paginated response lists, without content attribute"
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        sort:
          $ref: "#/components/schemas/Sort"
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        pageable:
          $ref: "#/components/schemas/Pageable"
        numberOfElements:
          type: integer
        size:
          type: integer
        empty:
          type: boolean
      required:
        - totalElements
        - totalPages
        - sort
        - first
        - last
        - number
        - pageable
        - numberOfElements
        - size
        - empty

    Sort:
      type: object
      format: sort
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
      required:
        - sorted
        - unsorted
        - empty

    Pageable:
      type: object
      format: pageable
      properties:
        page:
          type: integer
        size:
          type: integer
        sort:
          type: array
          items:
            type: string
      required:
        - page
        - size
        - sort
