services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=u3iGTeLr
      - POSTGRES_USER=db_user
      - POSTGRES_DB=dev
volumes:
  postgres-data:
