apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: 24ws-ase-pr-qse-05
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: dev
            - name: POSTGRES_USER
              value:  db_user
            - name: POSTGRES_PASSWORD
              value: u3iGTeLr
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: maestro-pvc-dev
