name: Build, Test and Push Docker Image

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build all Maven modules
        run: mvn clean compile --batch-mode

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run tests
        run: mvn test --batch-mode

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/heads/release/')
      
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build all Maven modules
        run: mvn install --batch-mode

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            TAG="${GITHUB_REF##refs/heads/release/}"
          else
            echo "No valid tag target, skipping image tagging."
            exit 1
          fi

          echo "Using tag: $TAG"
          docker build -t ghcr.io/$REPO_LOWER:$TAG .

      - name: Push Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            TAG="${GITHUB_REF##refs/heads/release/}"
          else
            echo "No valid tag target, skipping image push."
            exit 1
          fi

          docker push ghcr.io/$REPO_LOWER:$TAG
